import Head from 'next/head';
import Link from 'next/link';
import { useContext } from 'react';
import { Store } from '../utils/Store';

const Layout = ({ title, children }) => {
  const { state, dispatch } = useContext(Store);
  const cart = state.cart

  return (
    <>
      <Head>
        <title>{title ? title + ' | DC Day' : 'DC Day'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen  flex flex-col justify-between">
        <header>
          <nav className="flex h-16 items-center px-16  justify-between">
            <Link href="/">
              <a className="text-lg font-bold"> DC Day</a>
            </Link>
            <div>
              <Link href="/cart">


              <button type="button" className="inline-flex items-center px-5 py-2.5 text-sm text-center primary-button">
              Cart
  { cart.cartItems.length > 0 && ( <span className="inline-flex justify-center items-center ml-2 w-4 h-4 text-xs font-semibold text-blue-800 bg-blue-200 rounded-full">
  {cart.cartItems.reduce((a,item) => a + item.quantity , 0)}
  </span>)}
</button>


              
              </Link>
              <Link href="login">
                <a className="p-2">Login</a>
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>

        <footer className="flex h-10 justify-center items-center">
          Copyright @ 2022 DC Day
        </footer>
      </div>
    </>
  );
};

export default Layout;
